package org.openbank.service;

import org.springframework.stereotype.Component;

import java.security.SecureRandom;
import java.time.LocalDate;

/**
 * Generates bank card attributes used when an account request is approved.
 *
 * <p>Generated card numbers use the Luhn check digit so stored card data can be validated in tests
 * and transfer forms.</p>
 */
@Component
public class BankCardGenerator {

  private static final int CARD_NUMBER_LENGTH = 16;
  private static final int DEFAULT_VALID_YEARS = 4;

  private final SecureRandom random = new SecureRandom();

  /**
   * Generates a 16-digit card number with a valid Luhn checksum.
   *
   * @return generated card number as digits only
   */
  public String generateCardNumber() {
    StringBuilder cardNumber = new StringBuilder(CARD_NUMBER_LENGTH);
    cardNumber.append('4');

    while (cardNumber.length() < CARD_NUMBER_LENGTH - 1) {
      cardNumber.append(random.nextInt(10));
    }

    cardNumber.append(calculateCheckDigit(cardNumber.toString()));
    return cardNumber.toString();
  }

  /**
   * Calculates the default card expiry date.
   *
   * @return first day of the month four years from today
   */
  public LocalDate generateExpiryDate() {
    return LocalDate.now()
        .plusYears(DEFAULT_VALID_YEARS)
        .withDayOfMonth(1);
  }

  /**
   * Generates a three-digit CVV value for the demo banking domain.
   *
   * @return numeric CVV from 100 to 999
   */
  public String generateCvv() {
    return String.valueOf(random.nextInt(900) + 100);
  }

  /**
   * Validates that a card number has 16 digits and passes the Luhn checksum.
   *
   * @param cardNumber card number entered by the user or generated by the system
   * @return {@code true} when the format and checksum are valid
   */
  public boolean isValidCardNumber(String cardNumber) {
    if (cardNumber == null || !cardNumber.matches("\\d{16}")) {
      return false;
    }

    int sum = 0;
    boolean doubleDigit = false;

    for (int i = cardNumber.length() - 1; i >= 0; i--) {
      int digit = Character.getNumericValue(cardNumber.charAt(i));

      if (doubleDigit) {
        digit *= 2;
        if (digit > 9) {
          digit -= 9;
        }
      }

      sum += digit;
      doubleDigit = !doubleDigit;
    }

    return sum % 10 == 0;
  }

  private int calculateCheckDigit(String cardNumberWithoutCheckDigit) {
    int sum = 0;
    boolean doubleDigit = true;

    for (int i = cardNumberWithoutCheckDigit.length() - 1; i >= 0; i--) {
      int digit = Character.getNumericValue(cardNumberWithoutCheckDigit.charAt(i));

      if (doubleDigit) {
        digit *= 2;
        if (digit > 9) {
          digit -= 9;
        }
      }

      sum += digit;
      doubleDigit = !doubleDigit;
    }

    return (10 - (sum % 10)) % 10;
  }
}
